package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/RenterRus/sausage-bff/internal/graph/general/generated"
	"github.com/RenterRus/sausage-bff/internal/graph/general/model"
)

// UpsertTask is the resolver for the upsertTask field.
func (r *mutationResolver) UpsertTask(ctx context.Context, input model.UpsertTaskInput) (*model.TaskOperationResult, error) {
	panic(fmt.Errorf("not implemented: UpsertTask - upsertTask"))
}

// DeleteTaskByUser is the resolver for the deleteTaskByUser field.
func (r *mutationResolver) DeleteTaskByUser(ctx context.Context, userID string, transactionUUID *string) (*model.TaskOperationResult, error) {
	panic(fmt.Errorf("not implemented: DeleteTaskByUser - deleteTaskByUser"))
}

// SetCompleteStatus is the resolver for the setCompleteStatus field.
func (r *mutationResolver) SetCompleteStatus(ctx context.Context, userID string, complete *bool, transactionUUID *string) (*model.TaskOperationResult, error) {
	panic(fmt.Errorf("not implemented: SetCompleteStatus - setCompleteStatus"))
}

// SelectTasksByUser is the resolver for the selectTasksByUser field.
func (r *queryResolver) SelectTasksByUser(ctx context.Context, userID string) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: SelectTasksByUser - selectTasksByUser"))
}

// GetProfile is the resolver for the getProfile field.
func (r *queryResolver) GetProfile(ctx context.Context) (*model.Profile, error) {
	panic(fmt.Errorf("not implemented: GetProfile - getProfile"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
