// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Profile struct {
	Login *string `json:"login,omitempty"`
}

type Query struct {
}

type Task struct {
	TransactionUUID *string `json:"transactionUuid,omitempty"`
	Title           string  `json:"title"`
	Comment         *string `json:"comment,omitempty"`
	Priority        int32   `json:"priority"`
	StartDate       *string `json:"startDate,omitempty"`
	Complete        bool    `json:"complete"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type TaskOperationResult struct {
	Status string `json:"status"`
}

type UpsertTaskInput struct {
	TransactionUUID *string `json:"transactionUuid,omitempty"`
	Title           string  `json:"title"`
	Comment         *string `json:"comment,omitempty"`
	Priority        int32   `json:"priority"`
	StartDate       *string `json:"startDate,omitempty"`
	Complete        bool    `json:"complete"`
}
